columnSuffix: null
handle: clientLogos
instructions: null
name: 'Client Logos'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:49d3d537-a9f7-479a-a98f-12f75fbef05a' # Images
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:49d3d537-a9f7-479a-a98f-12f75fbef05a' # Images
  restrictedLocationSubpath: null
  selectionLabel: 'Add a client'
  showCardsInGrid: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
