columnSuffix: znqyemto
contentColumnType: text
handle: textBlock
instructions: null
name: 'Text Block'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2f555ca1-7a5e-4f57-9273-ba026e11f7c8 # Simple
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
